import type { Metadata } from 'next'
import { primary, secondary } from '@/styles/font'
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${primary.variable} ${secondary.variable}`}>
        {children}
      </body>
    </html>
  )
}
